eureka:
  client:
    serviceurl:
      defaultZone: http://localhost:8010/eureka/
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookservicecloud?serverTimezone=Europe/Warsaw&createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


